// SPDX-License-Identifier: AGPL-3.0-or-later
// Reusable settings entry with inline editing

import { Typography, FilledButton, TextButton, ListTile, MaterialText,
         MaterialPalette, TextField } from "@material";
import { MainAdapter } from "./main_adapter.slint";

export component SettingItem {
    in property <int> idx;
    in property <string> label;
    in property <string> value;
    in property <string> description;

    width: 100%;
    min-height: 72px;

    if !MainAdapter.show-edit-ui || MainAdapter.editing-field-index != root.idx: ListTile {
        width: 100%;
        text: root.label;
        supporting-text: root.description;
        clicked => {
            MainAdapter.start-edit(root.idx);
        }

        HorizontalLayout {
            spacing: 8px;
            Rectangle {
                max-width: 260px;
                height: 30px;
                border-radius: 10px;
                background: MaterialPalette.surface-container-highest;
                min-width: value-label.min-width + 18px;
                value-label := MaterialText {
                    x: 9px;
                    text: root.value;
                    style: Typography.label-medium;
                    color: MaterialPalette.on-surface-variant;
                    overflow: elide;
                }
            }

            MaterialText {
                text: "Edit";
                style: Typography.label-medium;
                color: MaterialPalette.primary;
            }
        }
    }

    if MainAdapter.show-edit-ui && MainAdapter.editing-field-index == root.idx: HorizontalLayout {
        spacing: 12px;
        padding-left: 10px;
        padding-right: 6px;
        padding-top: 9px;
        padding-bottom: 9px;
        width: 100%;

        MaterialText {
            text: root.label;
            style: Typography.label_small;
            vertical-alignment: center;
            min-width: 100px;
        }

        editor := TextField {
            horizontal-stretch: 1;
            text <=> MainAdapter.edit-value;
        }

        TextButton {
            text: "Cancel";
            clicked => {
                MainAdapter.cancel-edit();
            }
        }

        FilledButton {
            text: "Save";
            clicked => {
                MainAdapter.save-setting(root.idx, editor.text);
            }
        }
    }
}
